Repository Shrvangowda/hacktoFirst, pull requests merged in 2022-10, with the labels that each got.

#1 hackto challenge
  max_sub_array.py
Labels: hacktoberfest

#3 new files added
  max_consecutive_ones.py
  removeDuplicate.py
  romanToInteger.py
Labels: hacktoberfest

#5 Add files via upload
  testimonial-box-switcher/index.html
  testimonial-box-switcher/script.js
  testimonial-box-switcher/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#6 Add files via upload
  animated-countdown/index.html
  animated-countdown/script.js
  animated-countdown/style.css
Labels: hacktoberfest-accepted

#7 Add files via upload
  toast-notification/index.html
  toast-notification/script.js
  toast-notification/style.css
Labels: hacktoberfest-accepted

#8 Add files via upload
  sticky-navigation/index.html
  sticky-navigation/script.js
  sticky-navigation/style.css
Labels: hacktoberfest-accepted

#9 Add files via upload
  3d-boxes-background/index.html
  3d-boxes-background/script.js
  3d-boxes-background/style.css
  _project_starter_/index.html
  _project_starter_/script.js
  _project_starter_/style.css
Labels: hacktoberfest-accepted
